import type { VinylProject } from './types';

export const projects: VinylProject[] = [
  {
    id: 'cochlear-sonic',
    title: 'Sonic',
    subtitle: 'Cochlear — Design System',
    coverGradient: 'linear-gradient(155deg, #e8e2d8 0%, #d8d0c4 55%, #c8bfb0 100%)',
    spineColor: '#2e3d5a',
    accentColor: '#2e3d5a',
    coverImage: '/images/cochlear.webp',
    year: '2023',
    description:
      'Led the expansion of Cochlear\'s design system — Sonic — from a web-only component library into a comprehensive multi-platform solution covering iOS, Android, and professional software. Consolidated over 250 styles down to 64 design tokens, establishing a single source of truth in Figma with a Figma-to-GitLab pipeline. Within six months, two major greenfield projects had adopted Sonic.',
    tags: ['Design Systems', 'Design Tokens', 'Multi-platform', 'Figma', 'Component Library'],
    links: [{ label: 'View Case Study', url: 'https://cailborg.com/design-systems-at-cochlear' }],
    waveParams: {
      waveFrequency: 1, waveAmplitude: 0.85, waveSpeed: 0.5, waveLayers: 1,
      distortion: 0.86, noiseScale: 0.5,
      colorA: '#ede7db', colorB: '#c1af8c', colorAccent: '#ede7db',
      colorMix: 1, grainAmount: 0.052, vignetteStrength: 0,
    },
  },
  {
    id: 'limepay-cosmic',
    title: 'Cosmic',
    subtitle: 'Limepay — Design System',
    coverGradient: 'linear-gradient(155deg, #08101e 0%, #0d2040 45%, #081828 100%)',
    spineColor: '#0d2040',
    accentColor: '#060f1c',
    coverImage: '/images/cosmic.png',
    year: '2022',
    description:
      'A flexible design system enabling hundreds of merchant brands to theme the Limepay checkout without breaking accessibility. Led UI design across core product and new innovation features, from tokens and components through to custom illustrations and stakeholder education.',
    tags: ['Design Systems', 'Tokenisation', 'Accessibility', 'Figma', 'UI Design'],
    links: [{ label: 'View Case Study', url: '/work/cosmic' }],
    waveParams: {
      waveFrequency: 1, waveAmplitude: 0.85, waveSpeed: 0.5, waveLayers: 1,
      distortion: 0.86, noiseScale: 0.5,
      colorA: '#292e40', colorB: '#284862', colorAccent: '#292e40',
      colorMix: 1, grainAmount: 0.052, vignetteStrength: 0,
    },
  },
  {
    id: 'tbyb',
    title: 'Try Before You Buy',
    subtitle: 'Limepay — Brand & Product',
    coverGradient: 'linear-gradient(155deg, #0c1530 0%, #162045 55%, #0a1228 100%)',
    spineColor: '#162045',
    accentColor: '#0c1530',
    coverImage: '/images/tbyb.png',
    year: '2022',
    description:
      'Brand, product, and service design for Limepay\'s retail TBYB offering — from competitor analysis and service blueprints through to high-fidelity prototypes. Built a distinctive visual identity with an energetic, contemporary aesthetic targeting younger consumers.',
    tags: ['Brand Identity', 'Product Design', 'UX Research', 'Prototyping', 'Retail'],
    links: [{ label: 'View Case Study', url: 'https://cailborg.com/tbyb' }],
    waveParams: {
      waveFrequency: 1, waveAmplitude: 0.85, waveSpeed: 0.5, waveLayers: 1,
      distortion: 0.86, noiseScale: 0.5,
      colorA: '#292e40', colorB: '#283261', colorAccent: '#292e40',
      colorMix: 1, grainAmount: 0.052, vignetteStrength: 0,
    },
  },
  {
    id: 'ofx-fox',
    title: 'FOX V1',
    subtitle: 'OFX — Design Operations',
    coverGradient: 'linear-gradient(155deg, #b02c0a 0%, #e04c18 50%, #f06030 100%)',
    spineColor: '#b02c0a',
    accentColor: '#902208',
    coverImage: '/images/fox.webp',
    year: '2021',
    description:
      'Repositioned design at OFX from a wireframing function to a strategic discipline. Established FOX V1 — a React component library and Figma system — reducing UI component work from 60–70% of designer time to near-zero, freeing teams for higher-level experience strategy.',
    tags: ['Design Ops', 'React', 'Component Library', 'Figma', 'Accessibility'],
    links: [{ label: 'View Case Study', url: 'https://cailborg.com/ofx-design-system' }],
    waveParams: {
      waveFrequency: 1, waveAmplitude: 0.85, waveSpeed: 0.5, waveLayers: 1,
      distortion: 0.86, noiseScale: 0.5,
      colorA: '#ff5e49', colorB: '#bf1717', colorAccent: '#ff5e49',
      colorMix: 1, grainAmount: 0.052, vignetteStrength: 0,
    },
  },
  {
    id: 'agl-fred',
    title: 'FRED',
    subtitle: 'AGL — Design Language System',
    coverGradient: 'linear-gradient(155deg, #1018a8 0%, #1a22cc 45%, #141ab8 100%)',
    spineColor: '#1a22cc',
    accentColor: '#1018a8',
    coverImage: '/images/fred.png',
    year: '2018',
    description:
      'Foundational Rules of Experience Design — AGL\'s end-to-end design language system. A full audit of all consumer touchpoints, WCAG 2.0 AA colour palette, systematic spacing and typography, a comprehensive Sketch component library, custom illustrations, and a dedicated microsite to host and communicate the system.',
    tags: ['Design Language', 'WCAG', 'Component Library', 'Illustration', 'Documentation'],
    links: [{ label: 'View Case Study', url: 'https://cailborg.com/agl-design-system' }],
    waveParams: {
      waveFrequency: 1, waveAmplitude: 0.85, waveSpeed: 0.5, waveLayers: 1,
      distortion: 0.86, noiseScale: 0.5,
      colorA: '#0e16a0', colorB: '#1a22cc', colorAccent: '#20d8e0',
      colorMix: 1, grainAmount: 0.052, vignetteStrength: 0,
    },
  },
  {
    id: 'crownbet-fanterpreter',
    title: 'Fanterpreter',
    subtitle: 'CrownBet — Campaign',
    coverGradient: 'linear-gradient(155deg, #0a1a2e 0%, #0f2a48 45%, #0c2038 100%)',
    spineColor: '#0f2a48',
    accentColor: '#0a1a2e',
    coverImage: '/images/crownbet.jpg',
    year: '2018',
    description:
      'An interactive branded tool matching NRL and AFL fans with their NBA equivalent during the playoffs — featuring custom jersey illustrations and a modular visual system handling thousands of team-combination variations. Generated $1,066,400 in direct betting revenue at a 16:1 ROI.',
    tags: ['Campaign', 'Illustration', 'Web Design', 'Animation', 'Interactive'],
    links: [{ label: 'View Case Study', url: 'https://cailborg.com/crownbet-fanterpreter' }],
    waveParams: {
      waveFrequency: 1, waveAmplitude: 0.85, waveSpeed: 0.5, waveLayers: 1,
      distortion: 0.86, noiseScale: 0.5,
      colorA: '#0e2440', colorB: '#e07820', colorAccent: '#e07820',
      colorMix: 1, grainAmount: 0.052, vignetteStrength: 0,
    },
  },
];
