import type { WaveParams } from './types';

export const wavePresets: Record<string, WaveParams> = {
  Ocean: {
    waveFrequency: 6,
    waveAmplitude: 0.3,
    waveSpeed: 1.0,
    waveLayers: 4,
    distortion: 0.15,
    noiseScale: 3.0,
    colorA: '#0a0a2e',
    colorB: '#0c2d48',
    colorAccent: '#2196f3',
    colorMix: 0.45,
    grainAmount: 0.02,
    vignetteStrength: 0.8,
  },
  Aurora: {
    waveFrequency: 4,
    waveAmplitude: 0.5,
    waveSpeed: 0.6,
    waveLayers: 5,
    distortion: 0.35,
    noiseScale: 4.0,
    colorA: '#0a0a20',
    colorB: '#1a3a2a',
    colorAccent: '#66ffb2',
    colorMix: 0.55,
    grainAmount: 0.015,
    vignetteStrength: 1.0,
  },
  Lava: {
    waveFrequency: 3,
    waveAmplitude: 0.4,
    waveSpeed: 0.4,
    waveLayers: 3,
    distortion: 0.5,
    noiseScale: 2.5,
    colorA: '#1a0a00',
    colorB: '#4a1500',
    colorAccent: '#ff6b35',
    colorMix: 0.6,
    grainAmount: 0.03,
    vignetteStrength: 1.2,
  },
  Minimal: {
    waveFrequency: 8,
    waveAmplitude: 0.15,
    waveSpeed: 0.5,
    waveLayers: 1,
    distortion: 0.05,
    noiseScale: 2.0,
    colorA: '#0a0a0f',
    colorB: '#1a1a25',
    colorAccent: '#4a4a6a',
    colorMix: 0.3,
    grainAmount: 0.025,
    vignetteStrength: 0.6,
  },
};
