import type { ParticleParams } from './types';

export const particlePresets: Record<string, ParticleParams> = {
  Silk: {
    gridDensity: 200,
    particleSize: 1.2,
    waveBands: 5,
    waveFrequency: 4.0,
    waveAmplitude: 0.2,
    waveSpeed: 0.5,
    scatter: 0.15,
    densityFalloff: 8.0,
    brightness: 1.5,
    color: '#ffffff',
    bgColor: '#000000',
    noiseAmount: 0.1,
    symmetry: 0.8,
  },
  Nebula: {
    gridDensity: 300,
    particleSize: 1.0,
    waveBands: 7,
    waveFrequency: 3.0,
    waveAmplitude: 0.15,
    waveSpeed: 0.3,
    scatter: 0.25,
    densityFalloff: 5.0,
    brightness: 1.2,
    color: '#a0a0ff',
    bgColor: '#050008',
    noiseAmount: 0.2,
    symmetry: 0.0,
  },
  Convergence: {
    gridDensity: 250,
    particleSize: 1.4,
    waveBands: 3,
    waveFrequency: 5.0,
    waveAmplitude: 0.35,
    waveSpeed: 0.7,
    scatter: 0.1,
    densityFalloff: 10.0,
    brightness: 1.8,
    color: '#ffffff',
    bgColor: '#000000',
    noiseAmount: 0.08,
    symmetry: 1.0,
  },
  Sparse: {
    gridDensity: 80,
    particleSize: 2.5,
    waveBands: 2,
    waveFrequency: 2.5,
    waveAmplitude: 0.12,
    waveSpeed: 0.2,
    scatter: 0.3,
    densityFalloff: 4.0,
    brightness: 2.0,
    color: '#e0e0e0',
    bgColor: '#0a0a0a',
    noiseAmount: 0.15,
    symmetry: 0.5,
  },
};
